module.exports = {
  STORAGE_CONNECTION_STRING: process.env.STORAGE_CONNECTION_STRING,
  STORAGE_ACCOUNT_NAME: process.env.STORAGE_ACCOUNT_NAME,
  STORAGE_ACCOUNT_KEY: process.env.STORAGE_ACCOUNT_KEY,
  GH_APP_ID: process.env.GH_APP_ID,
  GH_APP_KEY: process.env.GH_APP_KEY
};
